
public enum MessageType {
CONNECT_CLIENT,CONNECT_TELLER,LOGIN_REQ,USER_INFO_REQ,
LOGS_REQ,ACCOUNT_INFO,LOG_INFO,DONE,SUCCESS,FAIL,DEPOSIT,
WITHDRAW,ADD_USER,REMOVE_USER,TRANSFER,STATUS_CHANGE,
MAKE_ACCOUNT,LOGOUT
}
